var header = document.createElement('header');
header.classList.add('p-4');
var boxBrand = document.createElement('div');
var homeLink = document.createElement('a');
var pageTitle = document.createElement('h1');
var iconWallet = document.createElement('i');
iconWallet.classList.add('fas', 'fa-solid', 'fa-wallet', 'me-3');
var boxNav = document.createElement('div');
var listNav = document.createElement('ul');
var balance = document.createElement('li');
var categories = document.createElement('li');
var reports = document.createElement('li');
var aBalance = document.createElement('a');
var aCategory = document.createElement('a');
var aReport = document.createElement('a');
var iconBalance = document.createElement('i');
var iconCategory = document.createElement('i');
var iconReport = document.createElement('i');
aBalance.appendChild(iconBalance);
aCategory.appendChild(iconCategory);
aReport.appendChild(iconReport);
aBalance.appendChild(document.createTextNode('Balance'));
aCategory.appendChild(document.createTextNode('Categoría'));
aReport.appendChild(document.createTextNode('Reportes'));
listNav.appendChild(balance);
listNav.appendChild(categories);
listNav.appendChild(reports);
boxNav.appendChild(listNav);
balance.appendChild(aBalance);
categories.appendChild(aCategory);
reports.appendChild(aReport);
pageTitle.appendChild(iconWallet);
pageTitle.appendChild(document.createTextNode('AhorrADAs'));
homeLink.appendChild(pageTitle);
boxBrand.appendChild(homeLink);
header.appendChild(boxBrand);
header.appendChild(boxNav);
document.body.appendChild(header);
header.classList.add('navbar', 'bg-success', 'bg-gradient', 'text-white', 'container-fluid', 'position-fixed');
listNav.classList.add('navbar-nav', 'me-auto', 'mb-2', 'mb-lg-0', 'list-group-horizontal');
reports.classList.add('nav-item', 'ms-3');
categories.classList.add('nav-item', 'ms-3');
balance.classList.add('nav-item', 'ms-3');
iconBalance.classList.add('fa-solid', 'fa-chart-column', 'me-1');
iconCategory.classList.add('fa-solid', 'fa-chart-column', 'me-1');
iconReport.classList.add('fa-solid', 'fa-chart-column', 'me-1');
